### ISSUE TITLE
Screenshot the Bouncer process

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/interlock-bouncer#125]
We need to screenshot the process of Bouncer deleting a malicious URL.
* Stills for documentation & marketing
* A short video for marketing??
  * @Treevuhh lmk about this^^

@jmercouris we need a URL that consistently gets blocked by Bouncer for this bad boy

**Comment by Treevuhh** [comment]
@DecentralizedDan I am in the process of finishing up the video. I see now that interlock.network is not detected as malicious anymore so I should have no problem completing it now. Give me a day or so and I'll send it to Andy and then update you.
 
The known malicious link that I have to use is https://phishing.com
Is there a different link I should be using in the video? @jmercouris

**Comment by jmercouris** [comment]
That link is suitable. I have made it always react as a malicious site!

**Comment by Treevuhh** [comment]
One step forward and one step back. Here is the screenshot of Bouncer working. But I quickly discovered as I was trying to re record the teaser video that Interlock.network is still being flagged as malicious by Bouncer @jmercouris @DecentralizedDan 

![Screenshot 2022-08-11 9 17 36 AM - Display 2](https://user-images.githubusercontent.com/95258773/184181533-7e72f79d-d0a0-4878-845c-53e98c99b598.png)
![Screenshot 2022-08-10 8 33 41 PM](https://user-images.githubusercontent.com/95258773/184181558-ded20c2b-88e1-4a73-a835-0a30e46ccad7.png)
