### ISSUE TITLE
[BUG] Remove link, tweak text from Bouncer reply message

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/interlock-bouncer#127]
Bouncer's reply to an allowlisted URL needs to be changed:
* Bouncer should post the URL in text, not as a hyperlink
* The text should read: "URL https://www.facebook.com/ marked safe by moderator." (not "by server owner")

**To Reproduce**
1. Type in an allowlisted URL
2. See error

**Expected behavior**
See above

**Screenshots**
<img width="517" alt="Screen Shot 2022-08-05 at 10 46 19 AM" src="https://user-images.githubusercontent.com/100495150/183132464-66a7be19-f00d-4ae3-85f1-a4a3e4de124e.png">

**Comment by jmercouris** [comment]
Fixed!
