### ISSUE TITLE
Mods should be able to remove URLs from allowlist

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/interlock-bouncer#131]
We need a feature that does `!allow_domains` in reverse
* Mods type in URLs and they get removed from the allowlist
* After success, user gets a success message
* If a URL is not allowlisted, it will say `URL(s) {} was not in the allow list.`
  * This obviously isn't too big a deal bc the URL they didn't want allowlisted wasn't even on it

**Comment by jmercouris** [comment]
Done!
