### ISSUE TITLE
[BUG] Issues with updating discord.py: Message Content Privileged Intent Update

### ISSUE THREAD

**Issue by nathan-jungels** [interlock-network/interlock-bouncer#169]
**Describe the bug**
Due to a change within Discord, handling of messages requires an additional intent. This change happened early August 2022. We may need to update settings within the Discord Application / Bot. We will definitely have to update the code to require the intent.

**To Reproduce**
1. Update discord.py to >=2.0.0.
2. Bot will no longer be able to see any messages.

**Expected behavior**
Bot should be able to see discord chat messages on latest discord.py update.

**Screenshots**
N/A

**Additional context**
[Discord.py: Information on Intents](https://discordpy.readthedocs.io/en/stable/intents.html)
[Discord: Message Content Intent FAQ](https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-FAQ)

**Comment by nathan-jungels** [comment]
@DecentralizedDan

**Comment by DecentralizedDan** [comment]
assigning this to @jmercouris

**Comment by jmercouris** [comment]
Luckily this only impacts verified bots, and those on more than 100 servers, so we have some time yet!
