### ISSUE TITLE
Make logs more compact and useful

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/interlock-bouncer#172]
Right now, the `#bouncer-log` channel is cluttered with expanded URL previews. 
* This makes the logging channel almost unreadable
* At the same time, logs are missing important information to give mods context

When a link is scanned as safe, it should say the following:
```
URL {STRING URL} marked as secure in #{CHANNEL}
```

NOTE: 
* If it is easy to implement, make the text `URL {STRING URL} marked as secure` a link to the message that triggered this log.

**Comment by jmercouris** [comment]
In progress.

**Comment by DecentralizedDan** [comment]
@jmercouris is this bad boy still in progress?

**Comment by jmercouris** [comment]
In my opinion, the logs are far more compact, and far more useful today. For now, this is done.
