### ISSUE TITLE
Log when unauthorized users attempt to invoke Bouncer commands

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/interlock-bouncer#176]
Log to `#bouncer-log` when an unauthorized user attempts to use a bouncer command

**Comment by jmercouris** [comment]
Do the usage of slash commands allow for this granularity?

**Comment by nathan-jungels** [comment]
@jmercouris - I would recommend catching the attempt via ```on_message``` event. Perhaps using a generated tree of slash commands from the existing bot.

**Comment by DecentralizedDan** [comment]
irrelevant with slash commands
