### ISSUE TITLE
change /allow_domain and /unallow_domain

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/interlock-bouncer#177]
`unallow_domain` in particular makes it sound like a URL will be added to a blocklist
* Change `/allow_domain` to `/add_to_allowlist`
* Change `/unallow_domain` to `/remove_from_allowlist`

**Comment by jmercouris** [comment]
`remove_domain_from_allowlist`?

**Comment by jmercouris** [comment]
Completed!
