### ISSUE TITLE
[BUG] Log entries for safe URLs are made twice by Bouncer

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/interlock-bouncer#183]
In the `#bouncer-log` channel, Bouncer is posting "marked as secure" messages twice
* Unsafe ones seem to only be posted once
* This can be seen in the Interlock `#bouncer-log` on September 29th:

<img width="519" alt="Screen Shot 2022-09-29 at 1 35 39 PM" src="https://user-images.githubusercontent.com/100495150/193136707-dad7dfbb-f7e3-45b5-bd09-674673028dc2.png">

**Comment by jmercouris** [comment]
My only hypothesis is that we have to signal some return value to avoid a signal being propagated again to the listener. Somehow calling the check twice. Will investigate!

**Comment by jmercouris** [comment]
Could not reproduce.
