### ISSUE TITLE
When a mod-posted URL gets deleted, Bouncer will explain how to allowlist the URL

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/interlock-bouncer#184]
**Background**: One of the top complaints about Bouncer is when it deletes URLs posted by mods. (inevitably safe URLs about the server's business)
* Mods usually don't know how to allowlist either, and don't look it up

**Feature**: When a URL posted by a mod gets deleted, Bouncer will add the following:
* "@{modname}: If you believe this URL is safe, use `/{allowlist command {URL} }` and then post the message again."

**Comment by jmercouris** [comment]
Complete with: b312a2e !
