### ISSUE TITLE
Detect Presence of Links

### ISSUE THREAD

**Issue by jmercouris** [interlock-network/interlock-bouncer#5]
Detect links with or without the protocol/properly formed suffix.

example:

`http://www.example.com`
`example.com`
`example dot com`

**Comment by jmercouris** [comment]
I've implemented a basic prototype of this. I am not satisfied yet with it, so I will keep this issue open. Too many ways to circumvent it.

**Comment by DecentralizedDan** [comment]
@jmercouris To make this ticket actually complete-able, let's put a meaningful, specific scope on it:
* Suggestion: Exactly what you put above in this ticket.
* Then lets make another ticket with some other invalid URL strings that are not detected yet
  * At a certain point, a person can malform a link to be human readable but not detectable by regex: `mailicioussite|)0tKONM` etc.
* Finally, eventually there will be a feature where humans can identify malicious URLs we fail to even detect
  * They will get rewarded with a fraction of the $INTR the user who posted the URL staked to post the link
