### ISSUE TITLE
Bouncer logs actions to a channel

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/interlock-bouncer#75]
*NOTE: For specific language, look at the discussion in https://github.com/interlock-network/interlock-bouncer/discussions/84 for draft language for the onboarding wizard. You can probably cut and paste directly from there or just use it for inspo.*

Bouncer will log its actions to a channel
* This is a familiar pattern for larger servers, which often have a `Security` channel monitored by multiple admins with different permissions, etc.
* Bouncer actions logged to a channel called `bouncer-log`, which should include the channel, user and URL, as well as admin name (if admin intervention was involved)
* If a user selects a public channel, there should be a confirmation step with the following language or similar:
  * `"The channel {name} is public, so all your users will be able to see everything Bouncer does -- including admin names when they use Bouncer on users who post unsafe URLs. Type 'yes' to confirm you want to log Bouncer's actions to a public channel."`

Bouncer will log to `bouncer-log` for a default level of detail and `bouncer-log-verbose` for a verbose level of detail.
* For all cases it should post: **channel + user + message + message ID**
* Default logging should only list malicious activity:
  * When BE says a URL is malicious
  * When users attempt to post a URL in a no-URLs channel #79 
  * When users attempt to post a non-allowlisted URL in an allowlist-only channel, eg #77 
  * When admin deletes a suspected-malicious URL #76 (incl admin name/ID)
  * When a user banned from posting links tries to do so #78 
* Verbose logging includes safe activity that Bouncer permits:
  * Channel + user + URL for allowlisted URLs posted
  * When BE says a URL is safe
  * SQL queries

**Comment by jmercouris** [comment]
Current status:

User cannot specify the channel.

**Comment by DecentralizedDan** [comment]
@jmercouris I have a couple suggestions here:
* Let's change the channel names
* The verbose logging channel will be `bouncer-log-verbose`
* The normal channel will be called `bouncer-log`
* And I'll change the scope of the ticket so it can be closed upon that change
  * We can revisit making the channel name customizable if users ask for it

What are the permissions for that channel?

**Comment by jmercouris** [comment]
I've updated the channel names in: bc0c99a

**Comment by DecentralizedDan** [comment]
@jmercouris would you consider this done?

**Comment by jmercouris** [comment]
I consider it done, for now.
